### ISSUE TITLE
Adding a reach-router

### ISSUE THREAD

**Issue by Abdurahmanov** [styleguidist/react-styleguidist#1056]
Hello!
I have a question. I saw [issue 993](https://github.com/styleguidist/react-styleguidist/pull/993#issuecomment-394105401), you mentioned the reach-router there, but I did not quite understand if you would use it. If so, can I help?

**Comment by sapegin** [comment]
I don't think we need a proper router, because 90% of Styleguidist is just one root component rendered with different props (basically list of components or sections to show). I _may_ be wrong here, but I don't see how something like Reach Router will solve any of our problems.

We have some [ugly code](https://github.com/styleguidist/react-styleguidist/blob/master/src/utils/handleHash.js) that parses the hash from the URL.

I'm fine with any solution that will make code easier to understand and maintain, and won't add a lot to our bundle. If you want to investigate that, it would SUPER AWESOME! 🦄
