### ISSUE TITLE
Don’t globalize user’s components

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1075]
Styleguidist makes all user’s components accessible in global scope which is [often problematic](https://github.com/styleguidist/react-styleguidist/issues/325).

Access to other components in examples isn't needed often — most of the time you only need to render a current component, so the idea is:

* Only current component is available in the example scope.
* Any other component should be explicitly required or imported.

Implementation details: 

We should prepend the example code with the component `require` the same way we do with `react` module:

https://github.com/styleguidist/react-styleguidist/blob/d66be96ccc4b23150b4d3ca659b01cbe35d0fe9d/loaders/examples-loader.js#L20-L21

And we should remove [globalizeComponents](https://github.com/styleguidist/react-styleguidist/blob/master/src/utils/globalizeComponents.js).

**Comment by mattwagl** [comment]
At first I was like: Oh no, this will make the examples much more bloated. But after thinking about it, it also makes them more realistic. So you can really copy and paste them into your app.

Additionally you also test the exports of your main module which is 👍 Because when doing styleguide driven development with styleguidist I tend to forget to export new components at the top level.

**Comment by sapegin** [comment]
Anyway it won't affect simple examples where you only use one component. But you'll have an ability to use explicit imports to make your code more realistic. See also #1076.

**Comment by okonet** [comment]
I love the idea! I think it’s  worth considering a list of global components via config, still. For example, I use layout primitives almost in every example and it will become much harder if I’d need to import Box and Stack components every time.

**Comment by sapegin** [comment]
That's possible now with `require` and `context` config options!

**Comment by joeljeske** [comment]
I agree is a problem, although I do not necessarily like the proposed solution. I do not want to have to `require()` or `import` each other component that I want. Additionally, I think it would be expected that it this pseudo-loader works exactly like the user's configured loader which of course is not realistic given the vast array of loader configurations. Because it likely cannot work exactly the same, it would be improbable to do an exact copy-paste.

What about something like this: 

All the components from the active module are available to the examples in the markdown. All other components are available only on the namespace of that component. That will keep it concise while making it clear that the example is using a component from different module. 

For example, if I had the components: 

```
// src/components/icon/icon.js
export { Icon }
```

```
// src/components/button/button.js
export { Button, LinkButton }
```


I would be able to use them as below: 

````
// src/components/icon/icon.md
```
<Icon name="settings" />
```
````

````
// src/components/button/button.md
```
<Button>Basic Button</Button>
```

``` 
<Button>
  <Icon.Icon name="next-arrow" />
  Button With Icon
</Button>
```
````

**Comment by sapegin** [comment]
I don't know what you mean by _pseudo-loader_, it uses webpack loaders of your project. Nothing has changed here.

**Comment by joeljeske** [comment]
I don’t know if it’s fair to say that it is very minor, I think it depends on the architecture of the given project. In a component centered framework, (especially when using css in js patterns) I think it can be more common to have a file that exports multiple components, especially those that are very small and work together and therefore should be documented together. 

Examples 

- text typography components (h1, h2, p, etc...)
- Building Block Components (e.g. Modal, ModalBody, ModalHeader etc...)
- layout primitives as mentioned by @okonet


IMO, It should be up to the author to decide if they want to create new files and docs for each of these micro components or keep them in a single file.

**Comment by kopax** [comment]
Hi, we are now experiencing issue in #1310  not being able to use `require` or `import` at all.

Could this be related?
