### ISSUE TITLE
Markdown parser doesn't support hard tabs for indentation

### ISSUE THREAD

**Issue by EvHaus** [styleguidist/react-styleguidist#1085]
**Current behavior**

When adding custom sections (as markdown files). the markdown parser doesn't seem to support tabs. So the following content:

```
Here is a list

* One
	* Two
		* Three
```

Is not rendered in a nested fashion. However, converting tabs to 4 spaces, fixes the issue.

**To reproduce**

```
// styleguide.config.js
{
	sections: [{
		content: 'README.md',
	}]
}

// README.md
Here is a list

* One
	* Two
		* Three
```

**Expected behavior**

Currently renders lists as:

![screen shot 2018-08-10 at 3 37 03 pm](https://user-images.githubusercontent.com/226640/43984103-40743cb6-9cb3-11e8-8f1c-043420c91461.png)

Should render as:

![screen shot 2018-08-10 at 3 37 21 pm](https://user-images.githubusercontent.com/226640/43984110-4c112a52-9cb3-11e8-8a12-59da5859e4a5.png)

**Comment by sapegin** [comment]
Please report the issue at [markdown-to-jsx](https://github.com/probablyup/markdown-to-jsx/).

**Comment by EvHaus** [comment]
@sapegin After investigation, this isn't an issue with `markdown-to-jsx`. It parses tabs just fine (as confirmed by trying on their demo site here: https://probablyup.com/markdown-to-jsx/)

After investigation, I can see that the markdown gets corrupted at the `<Section />` component BEFORE it even gets to the `markdown-to-jsx` compiler.

Here's a screenshot from the React dev tools showing the props.

![bug](https://user-images.githubusercontent.com/226640/44219727-9f20da80-a131-11e8-93eb-26b7ef228c1d.png)

My markdown file has this code:

```md
- some
- list
- another item

----

```

But the `<Example />` component receives this:

```markdown
-   some\n-   list\n-   another item\n\n* * *
```

Somehow the ruler got corrupted and the `----` code was changed to `* * *`

**Comment by sapegin** [comment]
We're reprinting Markdown from the AST using Remark:

https://github.com/styleguidist/react-styleguidist/blob/d66be96ccc4b23150b4d3ca659b01cbe35d0fe9d/loaders/utils/chunkify.js

https://github.com/styleguidist/react-styleguidist/blob/71d1425a1431d9fd7ba550ef8dc5770a43ef94ff/loaders/utils/highlightCodeInMarkdown.js

The fist issue (with `----`) only happens when you put the `----` after a list. I've investigated it a bit and it seems like a bug in markdown-to-jsx — https://github.com/probablyup/markdown-to-jsx/issues/206 — `* * *` is a valid horizontal line in Markdown.

The second issue looks like a bug in Remark — https://github.com/remarkjs/remark/issues/198
