### ISSUE TITLE
Drop React < 16.3 support

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1094]
This will allows us to use the new context API and other [new features](https://hackernoon.com/react-16-0-16-3-new-features-for-every-day-use-f397da374acf).

**This will be a breaking change, please make a branch based on the `next` branch.**

- [x] Rewrite context code to use the new API
- [x] Remove react-lifecycles-compat
- [x] Update [peerDependencies](https://github.com/styleguidist/react-styleguidist/blob/4ef206edece0b10fbc8404e6efa673dd38cf4406/package.json#L93-L96)

**Comment by rafaesc** [comment]
@sapegin can I take it?

**Comment by sapegin** [comment]
@rafaesc YES! That would be awesome! ❤️

**Comment by rafaesc** [comment]
I was trying to integrate the new context API and in the project works perfect, how I expected, the tests failed, because, I have to change the integration in the tests providing the new context.

But there is an error in [dive](https://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html) function of enzyme, when it tries to find the components children.

I found this issue, that it relates

https://github.com/airbnb/enzyme/issues/1647

If it fixes, tests could pass

**Comment by sapegin** [comment]
Thank for investigation!

**Comment by sapegin** [comment]
Done in 10.0.0!
