### ISSUE TITLE
Support for Expo SDK

### ISSUE THREAD

**Issue by iagorm** [styleguidist/react-styleguidist#1106]
**Support for Expo SDK**

Actually there is no support for Expo SDK environment, the question is, it's gonna have one day?

**Making Support**

This will help a lot for new developers incoming into a project to work together.

**Comment by sapegin** [comment]
I have no idea what's Expo SDK, and how its support should look like. And what do you mean by "no support".

**Comment by iagorm** [comment]
Expo is a environment that uses React Native and wrappers it with built in API native modules, but some components doesn’t allow the use of expo because of the need to link native modules, but even though using this module don’t get working with the expo’s environment, my question is, this is possible to work with?

**Comment by sapegin** [comment]
I'm going to close this for now, feel free to open a more actionable issue, or better send a pull request.

**Comment by kopax** [comment]
HI @iagorm, I am currently trying to work with expo sdk 36 and react-styleguidist. Did you find a way to configure.

I can import very small component that involve `<View />`, `<Text />` but as soon as I start importing bigger components, the react-styleguidist can't start throwing error due to loader being incorrectly configured.

I have tryed to use `@expo/webpack-config` to create the webpack configuration but that didn't do the trick.

Did you sorted the things out? 

```

./node_modules/expo/build/launch/withExpoRoot.js 25:20
Module parse failed: Unexpected token (25:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         };
|         if (__DEV__) {
>             return (<RootErrorBoundary>
|           <AppRootComponent {...combinedProps}/>
|         </RootErrorBoundary>);
 @ ./node_modules/expo/build/launch/registerRootComponent.js 2:0-42 4:48-60
 @ ./node_modules/expo/build/Expo.js
 @ ./src/core/SplashScreenCore.js
 @ ./node_modules/react-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/react-styleguidist/lib/client/index.js
 @ ./node_modules/react-styleguidist/lib/client/index.js
 @ multi ./styleguide/setup.js ./node_modules/react-styleguidist/lib/client/index ./node_modules/react-dev-utils/webpackHotDevClient.js
```

@sapegin, expo is equivalent to create-react-app in the react-native ecosystem. It's quite big, it work for the web and native, but the api for the web is a bit more restricted. Nothing bad, you can still do `.web.js` or `.ios.js` to import environment specific component. You can even use it like create-react-app just to build a web app and get used to the flexbox and native programming style. It should be supported by react-styleguidist at some point.

**Comment by kopax** [comment]
React-native is not supported by default, trying to render a view will makes styleguidist crash due to loader configuration:

```bash
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class SafeView extends Component {
>   static setStatusBarHeight = height => {
|     _customStatusBarHeight = height;
|   };

```

Would be nice to have some help on this. It's webpack configuration.

**Comment by kopax** [comment]
https://github.com/styleguidist/react-styleguidist/tree/master/examples/react-native
