### ISSUE TITLE
Highlight currently selected page on sidebar

### ISSUE THREAD

**Issue by jkarttunen** [styleguidist/react-styleguidist#1186]
**The problem**

On styleguides with a lot of content, it easy to get lost on where you were on the sidebar.

**Proposed solution**

A minimum useful solution would be highlighting (e.g. using background color) the currently selected page.

**Alternative solutions**

Related solutions would be 
- Supporting collapsible sections to enable better browsing of the main sections only.
- Scrolling the sidebar to right position when user arrives to the page using direct link.

**Comment by sapegin** [comment]
Feel free to send a pull request for that! ;-)

**Comment by cj** [comment]
@jkarttunen @sapegin according to this pull request https://github.com/styleguidist/react-styleguidist/pull/1195 it should be highlighting the sidebar.  Did this merged pull request get removed at some point?

**Comment by jure** [comment]
There's something funky going on on line https://github.com/styleguidist/react-styleguidist/blob/master/src/client/rsg-components/ComponentsList/ComponentsListRenderer.js#L51. Probably the link/href format has changed since then? You can temporarily fix this bit by overwriting the ComponentsListRenderer and changing this bit of the functionality.

**Comment by nathanmarks** [comment]
are you guys using `pagePerSection`? it doesn't seem to work with that option properly

**Comment by KesselRun-xyz** [comment]
Related: https://github.com/styleguidist/react-styleguidist/issues/1375

**Comment by jkarttunen** [comment]
@nathanmarks Yep, that was it.

**Comment by jkarttunen** [comment]
Closing as a duplicate of #1375
