### ISSUE TITLE
Styling text within back-ticks also affects the component props' styles

### ISSUE THREAD

**Issue by gazpachu** [styleguidist/react-styleguidist#1205]
They should have different styles, so that the props will not show a border around them.

<img width="493" alt="screen shot 2018-11-19 at 16 20 42" src="https://user-images.githubusercontent.com/1721288/48716201-170e0d80-ec17-11e8-87fc-2c356e85b36c.png">

<img width="503" alt="screen shot 2018-11-19 at 16 21 02" src="https://user-images.githubusercontent.com/1721288/48716229-23926600-ec17-11e8-8700-d6ab1a12c2e9.png">

In `styleguide.config.js`:

```
styles: {
    Code: {
      code: {
        fontSize: '14px',
        borderRadius: '5px',
        border: '1px solid #BCBEC0',
        background: '#F1F3F5',
        padding: '2px'
      }
    }
  },
```

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by gazpachu** [comment]
I'm looking at the `export function CodeRenderer(_ref2) {` in `lib/rsg-components/Code/CodeRenderer.js`. The _ref2 parameter seems to contain always the same class for both elements, the text within back-ticks and the component props text.

I wonder if we could pass an extra field inside `_ref2` to indicate that we want to style it a bit differently?

**Comment by sapegin** [comment]
Please don't look at the compiled code ;-)

I think you need to use custom styled instead of the `Code` component here:

https://github.com/styleguidist/react-styleguidist/blob/78db4281a915474aa8b4edc0c8883d3e2f93335e/src/rsg-components/Type/TypeRenderer.js#L16

And here:

https://github.com/styleguidist/react-styleguidist/blob/78db4281a915474aa8b4edc0c8883d3e2f93335e/src/rsg-components/Name/NameRenderer.js#L24

**Comment by gazpachu** [comment]
We missed fixing one item that still has the code styles:

<img width="584" alt="screen shot 2018-11-21 at 17 38 24" src="https://user-images.githubusercontent.com/1721288/48855459-62a9ee00-edb4-11e8-8b68-a81cff3717e7.png">

```
<code class="rsg--code-70">12</code>
```
