### ISSUE TITLE
Assets in production not loading when the publicPath in webpackConfig.output is defined

### ISSUE THREAD

**Issue by gazpachu** [styleguidist/react-styleguidist#1207]
This is related with #403 

When `publicPath` is defined in the `webpackConfig.output` object, the assets path in production lack the `publicPath` string.

The path should be: http://domain.tld/publicPath/assetName but it's rendering as http://domain.tld/assetName

```
dangerouslyUpdateWebpackConfig(webpackConfig) {
   if (process.env.NODE_ENV !== 'development') {
      webpackConfig.output = {
         publicPath: 'design-system/',
         filename: 'build/bundle.[chunkhash:8].js',
         chunkFilename: 'build/[name].[chunkhash:8].js'
      };
   }
   return webpackConfig;
}
```

**Comment by gazpachu** [comment]
Maybe we need something like an `assetsPublicPath`?

**Comment by sapegin** [comment]
> You may easily break Styleguidist using this options, try to use webpackConfig option instead.

I'm not sure there's an issue with Styleguidist, unless you see an easy fix.

**Comment by okonet** [comment]
Currently styleguidist sets `publicPath` to `''` making it impossible to configure it using `webpackConfig` property:

https://github.com/styleguidist/react-styleguidist/blob/1deb5473ddc13e5fe8ba4c2eb0d4172c13e0f5ac/src/scripts/make-webpack-config.ts#L50

Since I've been deploying the styleguide to `/styleguide` for all my styleguidist installations, I think would make sense to use [styleguideDir](https://react-styleguidist.js.org/docs/configuration.html#styleguidedir) by default and allow to override it via `webpackConfig` in the config.

Thoughts?

**Comment by stephenjason89** [comment]
@okonet have you found a solution to this?

**Comment by richard-lopes-ifood** [comment]
For those who have just arrived and are still facing this issue: you don't need to set the `publicPath` in webpack, but rather in the `template` property of the `react-styleguidist` configuration.
