### ISSUE TITLE
Imports in the basic example don't work

### ISSUE THREAD

**Issue by JelteF** [styleguidist/react-styleguidist#1232]
I was trying to convert my repo to 9.0.0-beta3, but couldn't figure out how to import other components in the scope. So I tried to use the example and that gave the same error.

**Current behavior**
The examples where an import takes place error out in the basic example.
![errors](https://i.imgur.com/HVUQoKW.png)

**To reproduce**
```
git clone https://github.com/styleguidist/react-styleguidist.git
cd react-styleguidist/examples/basic
npm install
npm install core-js # this seems to be depended on but wasn't in the package.json (other bug)
npx styleguidist server
```

**Expected behavior**
None of the examples have an error.

**Comment by sapegin** [comment]
Examples likely use the old version, feel free to send a pull request with a fix.

**Comment by JelteF** [comment]
My point was that I don't know how to fix it. I was looking at the examples
for how to fix it in my own project. Als the basic example actually uses
9.0.0-beta1, so afaik it should be up to date with the latest version.

**Comment by Sheparzo** [comment]
I’ve tried basic example with beta 1, 2, and 3 and found that none of them work always showing the reported error above. The example code all looks right. Could this be a problem with the implementation? Has something caused a regression of this awesome feature?

**Comment by sapegin** [comment]
There may be a problem with running examples _from_ the example folder because of some conflict with either `package.json` or Babel config or something else in the root folder. I'm using beta3 in a project without any issues and it does work when you run `npm start` in the root folder.

Feel free to fix the example though, or remove the incorrect instructions from its readme.

None of these issue are with Styleguidist itself.
