### ISSUE TITLE
Upgrade to react-icons 3

### ISSUE THREAD

**Issue by trollepierre** [styleguidist/react-styleguidist#1318]
**Current behavior**
When I run `yarn install`, I got 
error https://registry.yarnpkg.com/react-icons/-/react-icons-2.2.7.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/Users/myUserName/Library/Caches/Yarn/v4/npm-react-icons-2.2.7-d7860826b258557510dac10680abea5ca23cf650/node_modules/react-icons/lib/fa/sort-alpha-desc.js'"

**Expected behavior**

Using packages that are available on npm

**Comment by sapegin** [comment]
This looks like a network issue on your end, but feel free to send a pull request with update.

**Comment by JayaKrishnaNamburu** [comment]
Hey @sapegin is this still available ?

**Comment by sapegin** [comment]
Sure!


Artem Sapegin, sapegin.me

**Comment by JayaKrishnaNamburu** [comment]
Thank you, will update with a PR shortly 👍

**Comment by JayaKrishnaNamburu** [comment]
Hey @sapegin  update regarding this

1. The package react-icons with version number 2.2.7, is still available via the same link that is mentioned in the issue and with npm and yarn as well.

2. When i tried to upgrade the test cases were failing, because it turns out in version 3 they have made some major changes and files like ``react-icons/lib/md/fullscreen`` are not available in the same path, either we need to check and update the icons with the compatible one in the new set.
