### ISSUE TITLE
HTML comments visible as plain text

### ISSUE THREAD

**Issue by FezVrasta** [styleguidist/react-styleguidist#1326]
**Current behavior**

Markdown files containing HTML comments (`<!-- ... -->`) are visible as plain text since the upgrade to 9.x (9.0.5).

**To reproduce**

Sorry I don't have time to create a repro, but it's straight forward to reproduce.

**Expected behavior**

The HTML comments should be hidden when rendered.

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.

**Comment by eragon512** [comment]
@FezVrasta @sapegin I want to take up this issue, however, I am unable to reproduce this issue with the mentioned version `react-styleguidist@9.0.5`. Any idea on how to reproduce it?

**Comment by FezVrasta** [comment]
Can you look at https://github.com/quid/refraction please? You can reproduce it in that repository, you just need to comment out the manual workaround I added.

I'm sorry but my home is without electricity until Monday so I can't be more helpful 😞

**Comment by eragon512** [comment]
@FezVrasta  the issue seems to be with the `markdown-to-jsx` dependency => this dependency failes to recognise multiline (comments internally spaced with `\n`) HTML comments.

@sapegin This is a live demo of the dependency, for confirmation: https://probablyup.com/markdown-to-jsx/. You can confirm the issue by trying to enter any multiline HTML comment on the demo input.

**Comment by eragon512** [comment]
@sapegin sent a PR with a test to reflect this issue

**Comment by eragon512** [comment]
Created a corresponding issue in probablyup/markdown-to-jsx#246 for this, will need follow-up

**Comment by eragon512** [comment]
Um, updated the above test PR with a fix to close out this issue #1347
