### ISSUE TITLE
Upgrade react-docgen to 5.0.0 beta

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#1354]
[A new version](https://github.com/reactjs/react-docgen/releases/tag/v5.0.0-beta.1) has TypeScript support, so no need to extra plugins anymore. 

- [ ] Use `tsType` similar to `flowType`.
- [ ] Update docs, remove all mentions to react-docgen-typescript.

**This is a breaking change.** Should be based on #1288.

**Comment by smashercosmo** [comment]
So are we going to merge #1288 first? Or maybe I can just add additional commits to #1288?

**Comment by sapegin** [comment]
Merging will block master for other possible releases, and since both changes are breaking it would be better to continue in the same PR. This would be super cool actually ;-)

**Comment by smashercosmo** [comment]
ok, I'm on it

**Comment by sapegin** [comment]
@smashercosmo Did you have time to work on that? Need any help? 🦄

**Comment by smashercosmo** [comment]
Started working on it. Haven't finished yet ( I'll try to finish on weekends

**Comment by vvkee** [comment]
@smashercosmo Cool!!

**Comment by smashercosmo** [comment]
Seems like https://github.com/Jmeyering/react-docgen-annotation-resolver doesn't work with react-docgen@5.0.0. So first we need to submit PR there.

**Comment by smashercosmo** [comment]
mmm... guys @sapegin @okonet  you could just tell me that you're fine having react-docgen-annotation-resolver code in styleguidist repo, because I've spent my time doing exactly the same PR as https://github.com/styleguidist/react-styleguidist/pull/1387, but was waiting for any response from the react-docgen-annotation-resolver repo owner.

**Comment by sapegin** [comment]
@smashercosmo I'm so sorry 😢I was going to ask you to push what you have done so far but @okonet was too fast with this PR. Mind reviewing it?

> was waiting for any response from the react-docgen-annotation-resolver repo owner

Me too. I've sent them an email asking to transfer the repo to our org if they don't want to maintain it. But for now let's keep a fork.

**Comment by okonet** [comment]
@smashercosmo that’s actually exactly the code you wrote. I’d love you to take the ownership of this package as soon as we have basic monorepo setup for this project. The reason I copied it over is exactly the same you mentioned: I wanted to try integrating it without waiting for the whole review and merge process. You’re welcome to jump on this branch and help me finilazing it but it looks like it won’t work without some fixes on React-docgen side. Here is the related issue: https://github.com/reactjs/react-docgen/issues/375

**Comment by smashercosmo** [comment]
@okonet yeah, ok, I understand things like that happen in OSS. Just was a bit upset, because my not-pushed PR was almost the same as yours (I mean not only the react-docgen-annotation-resolver part :)) But of course I would be happy to help with both getting https://github.com/styleguidist/react-styleguidist/pull/1387 merged and with whatever other styleguidist issues you'd like to resolve. I use styleguidist heavily in my work and definitely want to contribute back.

**Comment by okonet** [comment]
@smashercosmo don’t be! I was just eager to try integrating it after chatting with Artem :-). We can continue with your PR but as I mentioned that doesn’t solve all the issues.  Which brings me to the next question: should we skip the annotated components for now?

**Comment by smashercosmo** [comment]
@okonet well, we can always write our own custom handler for extracting types from styled-components.

**Comment by okonet** [comment]
I tried and gave up. Do you want to give it a try?

**Comment by smashercosmo** [comment]
Yeah, I can try)

**Comment by omninonsense** [comment]
Are there any updates regarding this?
