### ISSUE TITLE
Compilation error on using 'async' and 'await' in readme.md

### ISSUE THREAD

**Issue by gargroh** [styleguidist/react-styleguidist#1371]
**Current behavior**

When using async functions in readme.md then getting compilation error, before upgrading to 9.x.x it was working fine. 
Error :-
![image](https://user-images.githubusercontent.com/42495927/58002894-32da6980-7afd-11e9-82e2-d67ffd1c69ec.png)

Simplified code :-
![image](https://user-images.githubusercontent.com/42495927/58003423-5eaa1f00-7afe-11e9-9aa4-bece1f55f449.png)

**To reproduce**
Just try to use async functions in readme.md, it can be easily replicated.

**Expected behavior**

It should compile perfectly as it doing for 8.x.x

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.

**Comment by mendrew** [comment]
### The error explanation
We have the error here because styleguidinst has updated version of [bublé](https://github.com/bublejs/buble) ([from v0.9.4 to v0.9.7](https://github.com/mendrew/react-styleguidist/commit/48f72208d6cfb19e34654f22b47c86d8531e2b71#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34)) which does actual code transformation.
In latest version of bublé they throw this error because right now [bublé cannot transpile async](https://github.com/bublejs/buble/issues/109#issuecomment-380854164), so they've added a special transform option called `asyncAwait` to pass `async` through as before. Here the code, how they do it: [example](https://github.com/bublejs/buble/blob/086d895cdd616de065bf82339567ed4f0bc44b75/src/program/types/ArrowFunctionExpression.js#L6-L12)

It has been working before because bublé just passed `async` through.
Right now it throws the error, but you are able to confgure bublé to pass async through without transformation by using [compilerConfig](https://react-styleguidist.js.org/docs/configuration.html#compilerconfig) in your `styleguide.config.js`.
Like this: 
```js
  compilerConfig: {
    transforms: { asyncAwait: false }
  }
```

It also makes sence to pass default styleguidinst options for `compilerConfig` ([code](https://github.com/mendrew/react-styleguidist/blob/010761b5752ac43841aa54837c5562eddd8f9d82/src/scripts/schemas/config.js#L34-L45)), as documentation about default options is outdated.

### Questions
@sapegin Should we add ` transforms: { asyncAwait: false }` for default compilerConfig to make async/await work by default?
Does it make sense to update [compilerConfig](https://react-styleguidist.js.org/docs/configuration.html#compilerconfig) documentation to add there all current default options?
