### ISSUE TITLE
how to highlighting  java、ruby  language in *.md files

### ISSUE THREAD

**Issue by xudihui** [styleguidist/react-styleguidist#1378]
first of all,react-styleguidist is amazing! thanks very much!

this problem:
Warning: Syntax highlighting for “java” isn’t supported

**Comment by dysticus** [comment]
@xudihui The warning message says it all: 
`Warning: Syntax highlighting for “java” isn’t supported. Supported languages are: clike, markup, xml, html, mathml, svg, markdown, md, css, scss, javascript, js, flow, typescript, ts, jsx, tsx, graphql, json, bash, shell, diff.
`
A workaround would be to edit this file https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/utils/highlightCode.js#L3 to also include Ruby/Java from Prism, but it would be overwritten on a fresh `npm install`

@sapegin I understand why languages other then the most common used in component development are not part of the default. However, perhaps the API can change a bit so a user can decide which Prism highlighting to add to their bundle, instead of the current hardcoded list. What do you think?

**Comment by sapegin** [comment]
Sure, feel free to send a pull request.

**Comment by johanbook** [comment]
I am also interested in this. Is there some solution without editing `node_modules` or forking it?
