### ISSUE TITLE
Component name capitalization issue

### ISSUE THREAD

**Issue by okonet** [styleguidist/react-styleguidist#1381]
**Current behavior**

I've named my component `ButtonTS` but in the styleguide I see `ButtonTs`. It also affects auto-import of this component. In the `ButtonTS.md` I have

```jsx
<ButtonTS>Test</ButtonTS>
```

and this isn't working with the error `ReferenceError: ButtonTS is not defined` being shown.

If I change the example to

```diff
- <ButtonTS>Test</ButtonTS>
+ <ButtonTs>Test</ButtonTs>
```

then it works.

**To reproduce**

https://codesandbox.io/s/github/component-driven/component-driven-development/tree/typescript

**Expected behavior**

It should not change component name from `ButtonTS` to `ButtonTs`

**Comment by mendrew** [comment]
I think that I found the reason, it is this function. 
https://github.com/styleguidist/react-styleguidist/blob/5ff72d8c82d11ce70c6449a77343e2cc5462c037/src/loaders/utils/getNameFromFilePath.js#L4-L11

It is used here to define `displayName`
https://github.com/styleguidist/react-styleguidist/blob/5ff72d8c82d11ce70c6449a77343e2cc5462c037/src/loaders/utils/getProps.js#L136-L139

We do `_.camelCalse` for the whole string. So `ButtonTS` becomes `ButtonTs`.

I'm looking at test cases:
https://github.com/styleguidist/react-styleguidist/blob/5ff72d8c82d11ce70c6449a77343e2cc5462c037/src/loaders/utils/__tests__/getNameFromFilePath.spec.js#L4-L24

### Questions
1. What if we just do camelCase for `-` cases?

2. At the same time this is happening because `doc.displayName` is not defined.
I see warning about this which is comming from propsParser (which is in the mentioned repo is default `react-docgen`)
```
Warning: src/components/core/ButtonTS/ButtonTS.tsx matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.
```

So, react-docgen is probably failed here. What if try `react-docgen-typescript` as a [propsParser](https://react-styleguidist.js.org/docs/webpack#create-react-app-with-typescript) 
I've tried but failed. Not really good at TS and it's configuration..

**Comment by okonet** [comment]
Why do even need to modify the component's name? Is it when the parser failed to infer it from the component? I'd say in this case it should be less obtrusive and only convert if necessary.

Probably we should warn users about that behavior in the console?

**Comment by mendrew** [comment]
> Why do even need to modify the component's name? Is it when the parser failed to infer it from the component?

Yes, it is.
As I can see from the PR which has implemented this (https://github.com/styleguidist/react-styleguidist/pull/672)
here the quote:  
> Components that react-docgen does not recognize as react-components will still be included in the style guide. The displayName for such components is guessed based on the file name.

What about a warning like: `propsParser can't recognize the component. The displayName will be guessed based on the file name.`?

**Comment by okonet** [comment]
@mendrew it say it should display the warning. I'm wondering if we should make it more explicit in this case? Also, I think the algorithm change proposed by @sapegin in the PR is the root cause of the problem. In the original implementation it would not change capitalized characters AFAIK:

https://github.com/nerdlabs/react-docgen-displayname-handler/blob/8cd141064910eb429f18e03e631a25cec371330a/source/index.js#L65

I'd propose to revert back to the implementation we copied from and add a separate test case. 

@mendrew do you want to submit a PR?

**Comment by mendrew** [comment]
Yes, I do want to submit a PR.

So, you are suggesting
1.  to replace  
```js
_.upperFirst(_.camelCase(displayName)); 
```  
  By something like this  
```js
return displayName
    .charAt(0).toUpperCase()
    .concat(displayName.slice(1))
    .replace(/-([a-z])/, (_, match) => match.toUpperCase());
```

Yes, it will fix your case.

2. display an explicit warning for this case.
If you have an idea about the proper format I'd love to see.
What exactly would be valuable to show to the user? The fact that parser is failed. And that the component displayName is guessed based on the file name, and the displayName value.

**Comment by okonet** [comment]
I'd double check 2 and if there is a warning already I wouldn't touch it. In other words, I'd only focus on the bugfix (since it's a bug) and would keep the surface of the changes as low as possible. I'd also add a test for this edge case.

Thanks!

**Comment by mendrew** [comment]
Ok, I got it, thank you!
