### ISSUE TITLE
setting maxWidth for only one component page

### ISSUE THREAD

**Issue by a-gheorghe** [styleguidist/react-styleguidist#1390]
Hey,

I am looking to document some responsive layout (Grid, Row, Column)  components but am having trouble showing the responsiveness of the Grid component. The component takes two properties (fluid and center) that apply to the Grid when the viewport is above 1400px. However, the main content section does not expand beyond 1000px.

I tried setting the maxWidth property in theme to 2000px and this works and allows me to show the different configurations for the Grid component, but I don't like how this larger maxWidth looks with other components.

Is it possible to set maxWidth specifically for one page but leave the others unaltered?

**Comment by jkarttunen** [comment]
AFAIK, responsive components that rely on page width are difficult to do at the moment, because
1. The navigation is on the left hand side, and takes some width from the layout
2. The components are not iFramed

I guess it would be possible to create some kind of iframe wrapper for the component, but upcoming features might help with this. Right @sapegin ?

**Comment by jkarttunen** [comment]
But i guess you could customize the StyleGuide.js as in the customized example, and add a if condition to change the maxWidth in single route
