### ISSUE TITLE
Rendering named export instead of default export when using HOC

### ISSUE THREAD

**Issue by vollmerr** [styleguidist/react-styleguidist#1413]
**Current behavior**

The named export of a component is being used instead of the default if the default export is using a HOC. 

I was on 9.1.5 and it worked fine for using the default export with a HOC, but trying to update to 9.1.13 makes it render the named export instead of the default.

**To reproduce**

Using 9.1.5 it renders the button text that is overridden in the HOC
https://github.com/vollmerr/example/tree/default-export-9.1.5

Using 9.1.13 it renders the button text passed directly to the component in the example (not using the HOC)
https://github.com/vollmerr/example/tree/named-export-9.1.13

**Expected behavior**

It should still use the default export even when having a HOC (or is there a way to configure this that I missed?)

**Comment by mendrew** [comment]
This is because of a recent fix for named export. 
This issue: https://github.com/styleguidist/react-styleguidist/issues/1281

Commit: https://github.com/styleguidist/react-styleguidist/commit/5ff72d8c82d11ce70c6449a77343e2cc5462c037

As you can see the logic to get a component is ([code](https://github.com/styleguidist/react-styleguidist/commit/5ff72d8c82d11ce70c6449a77343e2cc5462c037#diff-f91bc49c7b1a5e3532b6a3f5c0d847e0R81))
```const name = name$0[name] || name$0.default || name$0;```

So, if we can get named export, then we will take it instead of default if nothing is specified explicetly.

Feel free to PR better approach or suggest the right way.
But as a temporary workaround you can try to explicetly import your component using it's default export.
Like
```
import Button from './Button'; // not sure about path
<Button text={'using named export'} />
```

Here you can find example with explicit named export and `RandomButton`
https://github.com/styleguidist/react-styleguidist/blob/5ff72d8c82d11ce70c6449a77343e2cc5462c037/examples/basic/src/components/RandomButton/Readme.md

**Comment by vollmerr** [comment]
Swapped to using explicit imports and looks to be working. 
Thanks for the explanation and quick response!
