### ISSUE TITLE
Property types don't show up

### ISSUE THREAD

**Issue by smashercosmo** [styleguidist/react-styleguidist#1551]
After upgrading to latest styleguidist (the one with native TS support) property types stopped showing up

![Screenshot 2020-03-11 at 14 06 17](https://user-images.githubusercontent.com/273283/76415867-ac03bf80-63a2-11ea-91dd-2cea45813f25.png)

**Current behavior**

With react-docgen-typescript you could see property types

**To reproduce**

Try to use react-styleguidist with TS

**Expected behavior**

You should be able to see property types

**Comment by mitsuruog** [comment]
I have the same issue. version is`v11.0.1`.

![react-styleguidist issues 1551 - CodeSandbox](https://user-images.githubusercontent.com/1703219/76431298-b9499a00-63f4-11ea-95dd-1f4650fb2bdb.png)

Here is my sandbox.

- https://codesandbox.io/s/react-styleguidistissues1551-1iyof

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix 👾

**Comment by mitsuruog** [comment]
In my case, there are 2 issues.

1. `react-docgen` does not parse the type of the component correctly.

The type of this component will not parse anything.

```tsx
export const Button: React.FC<ButtonProps> = props => {
  // ...
}
```

But this component can parse.

```tsx
export function Button(props: ButtonProps) {
  // ...
}
```

It might be an issue or limitation for `react-docgen`.

2. `react-styleguidist` does not render `tsType` even if `react-docgen` has parsed successfully.

`react-docgen` returns `tsType` including the type info, but the current version does not seem to handle this correctly.

**Comment by mitsuruog** [comment]
@sapegin I am working on it. 😉

**Comment by mitsuruog** [comment]
@sapegin I want to hear your opinion.

I am wondering how to display types in the UI for TypeScript.
It is a little different in the result of the UI from the way what the old version was. 
because for the TypeScript users, it used to use `react-docgen-typescript`, but now it uses `react-docgen`. 

ex)

If type is something like:

```
prop3: () => void;
```
 Old version:

```
Prop name: prop3
Type: () => void;
```
New version:

```
Prop name: prop3
Type: function
// NOTE: `() => void` goes to tooltip
```

![stylesheet-example-column](https://user-images.githubusercontent.com/1703219/76680739-81c63200-662e-11ea-8598-42d2d2133fe3.png)

Since I've been looking at the old version for a long time, the new version of the result feels a bit difficult to use. but it has an inconsistency for the result of `flowType`.

so should I keep the way for `react-docgen-typescript` or take consistency for the flowType.
