### ISSUE TITLE
Yarn add react-styleguidist does not install /lib/client/rsg-components/

### ISSUE THREAD

**Issue by emeeks** [styleguidist/react-styleguidist#1662]
It's just missing from the directory. If I copy it from the repo and add it, it runs fine. I haven't changed anything having to do with styleguidist at all.

**Comment by switchingkeyboards** [comment]
Same problem when installing with yarn.

**Comment by sapegin** [comment]
```
❯ yarn add react-styleguidist
❯ ls node_modules/react-styleguidist/lib/client
consts.d.ts  consts.js  index.d.ts  index.js  polyfills.d.ts  polyfills.js  rsg-components  styles  utils
```

**Comment by emeeks** [comment]
I'm sorry the title cut off the critical feature, it is installing `rsg-components` it is not installing `rsg-components/Examples` can you please take a look at that?

**Comment by sapegin** [comment]
That's why the issues template asks you to provide reproduction instructions.

**Comment by emeeks** [comment]
Sorry about that, I should have written in more detail in the original issue.

That's weird, I don't have the entire `Examples` directory nor does anyone on my team when they run yarn on the app where we're using styleguidist. If I copy it over from the original `src` from the repo, it works fine. Obviously you can't reproduce it, but do you have any ideas on what else I could look at?

**Comment by Etheryte** [comment]
While this is oddly specific, I ran into a similar problem when installing with Yarn. In our case, the problem was a `.yarnclean` file which removed demo files and examples directories for packaging and shipping reasons. Highly unlikely that anyone else runs into the same exact problem, but maybe it will help someone else who steps into the same hole.
