### ISSUE TITLE
Cutting a release

### ISSUE THREAD

**Issue by kybradeck** [styleguidist/react-styleguidist#1673]
Hey team!

I'm wondering what the release process is like for getting react-styleguidist updated on npm? It looks like a release hasn't been made [since May 27](https://github.com/styleguidist/react-styleguidist/releases), and my team is waiting on a [vulnerability fix](https://github.com/styleguidist/react-styleguidist/pull/1658) that's been preventing us from using Styleguidist.

**Comment by sapegin** [comment]
I think we need to tweak semantic-release setting because it doesn't think there's anything to publish 🤷 

https://travis-ci.org/github/styleguidist/react-styleguidist/jobs/720900870

1. Remove this line:

https://github.com/styleguidist/react-styleguidist/blob/be90f3aa688e5d9f188686c7261d964157a338b6/.travis.yml#L68

2. Remove the config:

https://github.com/styleguidist/react-styleguidist/blob/master/release.config.js

3. Update the docs to the default Angular convention, instead of the ESLint one:

https://github.com/styleguidist/react-styleguidist/blob/master/docs/Maintenance.md#commit-message-conventions
