### ISSUE TITLE
HMR is broken

### ISSUE THREAD

**Issue by flunderpero** [styleguidist/react-styleguidist#1785]
**Current behavior**

When I run `styleguidist server` I get this in the browser console:

```
main.bundle.js:10926 Uncaught ReferenceError: process is not defined
    at eval (webpackHotDevClient.js:63)
    at Object../node_modules/react-dev-utils/webpackHotDevClient.js (main.bundle.js:4329)
    at __webpack_require__ (main.bundle.js:10923)
    at main.bundle.js:11966
    at main.bundle.js:11970
```
HMR is obviously not working. With webpack 5 `process` is no longer defined and the `webpackHotDevClient.js` first looks into `process.env` and then falls back to `location` in order to find the right HMR server. I think styleguidist just uses an old version.

The problem has been reported elsewhere, too: https://github.com/vue-styleguidist/vue-styleguidist/issues/1044

**To reproduce**

Just start styleguidist 11.1.6 in server mode and look into the browser console.

**Workaround**
My current workaround is to define `process.env` like this in `styleguide.config.js`:
```
    webpackConfig: {
        plugins:[
            new webpack.DefinePlugin({
                process: {env: {}}
            })
        ]
    }
```

**Comment by elevatebart** [comment]
@sapegin It feels like we could mock process, if it does not exist ;)
Should I make a PR?

**Comment by sapegin** [comment]
Sure, if that helps ;-)

**Comment by vileen** [comment]
Huh, weird, for me it helped but caused another error `WebSocket connection to 'ws://localhost:9000/sockjs-node' failed: `

**Comment by schorfES** [comment]
As @flunderpero [wrote](https://github.com/styleguidist/react-styleguidist/issues/1785#issue-867125112), it's caused due to a miss-match between the webpack version and the styleguidist webpack-configuration. Styleguidist targets v4 of webpack, while following the [getting started docs](https://react-styleguidist.js.org/docs/getting-started) v5 would be installed as latest version. If there are no other dependencies in you project to webpack at version 5, you should downgrade webpack by running `npm i -D webpack@4` – that helped me.

**Comment by adamjw3** [comment]
I've ran into the same error, i'm using next js and sass (webpack 5). @flunderpero i tried your fix with the plugins options but didn't work. can you share your full solution?
