### ISSUE TITLE
How do we document methods inside a functional component?

### ISSUE THREAD

**Issue by VigneshSubramaniam** [styleguidist/react-styleguidist#1833]
Let's say I have a component like below:
```
/**
 *
 * This is geting documented
 */
function MyComponent(props) {
  /**
   *
   * This is not getting documented
   */
  const foo = () => {
    console.log('I am not documented :(');
  };
  return <div>Hello world!</div>;
}
```
Methods just shows an empty array. Is there a way to document these kind of methods?

**Comment by tomas-hartman** [comment]
I personally think there is no straight solution to your problem with styleguidist. (And I would be happy to learn about it, if there was). There are three possible solutions that I tried previously:

- One way is to use other documentation tool like jsdoc that can do it, but that would mean that you'd have two documentations - technical and visual. 
- Other possible solution is to extract the inner function into a separate module, import it as some kind of helper function and document it as a separate module. Styleguide might however complain that it is not a component, but there might be some workarounds (I did not try to find them). It has one big advantage though, because as a module, you could also unit test your function. Ofc this is not worth the effort for simple "handleClick" methods.
- Third solution is not so elegant, but it is functional too (and it is the one we use): you can always make styleguidist show code of your component, which would mean that you'd be able to read the documentation right from code. 

Styleguidist is designed to document components, that can be used by other users, who might just want/need to use them and who need know how to do it, but who generally don't need to understand how they work inside, so there is no _need_ to document their inner methods (in styleguide). If they need so, they can look it up inside your code. That's at the least idea we use styleguidist with.

**Comment by sabhas** [comment]
Is there any way to resolve this issue other than @tomas-hartman suggestions?

**Comment by trpeel** [comment]
> Is there any way to resolve this issue other than @tomas-hartman suggestions?

Did you ever find a solution (or an alternative)?
