### ISSUE TITLE
Improve terminal output on style guide server start

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#470]
I like how it’s done in Create React App:

![](https://facebook.github.io/react/img/blog/cra-better-output.png)

* [ ] Show the URL only after successful compilation
* [ ] Show network URL
* [ ] Improve the UI

Most likely we can reuse some functions from [react-dev-utils](https://github.com/facebookincubator/create-react-app/blob/dc4ce606ef8b4c97aec0c80c20f8116e9795bb21/packages/react-dev-utils/WebpackDevServerUtils.js) (we already use it in Styleguidist), then this task will be relatively easy ;-)

**Comment by SaraVieira** [comment]
<img width="676" alt="screenshot 2017-06-11 10 33 09" src="https://user-images.githubusercontent.com/1051509/27009921-8ce863e0-4e91-11e7-89b5-3c98d981431b.png">

In this case what is the lan URL ?

**Comment by sapegin** [comment]
Take a look at CRA implementation (link in the description), they have all the code (and we probably can reuse it).

**Comment by SaraVieira** [comment]
That's exacly the code I have use, I just need to get the ip address of the
computer

**Comment by sapegin** [comment]
But they already have it ;-/

https://github.com/facebookincubator/create-react-app/blob/dc4ce606ef8b4c97aec0c80c20f8116e9795bb21/packages/react-dev-utils/WebpackDevServerUtils.js#L38-L88

**Comment by SaraVieira** [comment]
Le copy and le paste shall be made then :p

---

Thank You and Best regards

Sara Vieira

Front End Developer 

http://iamsaravieira.com
http://twitter.com/NikkitaFTW

On Sun, 11 Jun 2017 at 13:00 Artem Sapegin

<
mailto:Artem Sapegin <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

But they already have it ;-/

https://github.com/facebookincubator/create-react-app/blob/dc4ce606ef8b4c97aec0c80c20f8116e9795bb21/packages/react-dev-utils/WebpackDevServerUtils.js#L38-L88

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/styleguidist/react-styleguidist/issues/470#issuecomment-307624766
, or

**Comment by sapegin** [comment]
Try to reuse their code first ;-)

**Comment by SaraVieira** [comment]
Oh yeah , i'm still on master , just want to show the ui before I start working on it and get that approved first :)
<img width="486" alt="screenshot 2017-06-11 16 40 09" src="https://user-images.githubusercontent.com/1051509/27012279-a5ee33dc-4ec4-11e7-93ab-7ad44ebb171b.png">

**Comment by sapegin** [comment]
Looks cool! Could we remove this `npm run compile` notice? It’s incorrect anyway ;-)

* Style guide → style guide
* On Your Network →  On your network

**Comment by SaraVieira** [comment]
Sure! I'll create a branch and start working on this tonight :)

**Comment by sapegin** [comment]
Sounds good, thanks! 🍕

**Comment by sapegin** [comment]
@SaraVieira Do you have anything to pull request here? ;-)

**Comment by SaraVieira** [comment]
Damn @sapegin no :(
I'll get on this tomorrow, I'll use my new cli skills to make it awesome! 🎉🎉

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
