### ISSUE TITLE
Support for font-awesome icons

### ISSUE THREAD

**Issue by sabhyankarxactly** [styleguidist/react-styleguidist#591]
How do I get the font-awesome library to load in the styleguidist? I tried the method for loading external CSS (see below) but it does not load the font-awesome icons.

- Your style guide config (`styleguide.config.js`).
```js
const path = require('path');

module.exports = {
    components: 'src/components/**/index.js',
    showUsage: true,
    require: [
        path.join(__dirname, 'node_modules/font-awesome/css/font-awesome.css')
    ]
};
```
- Webpack version.
2.2.1
- Operating system, browser and version if it’s a layout bug.
Windows 10, Chrome v60

- Reproducible demo:
I can add a reproducible demo if required.

**Comment by n1313** [comment]
I bet you need to require the font file itself, too.

By the way, if your components depend on font-awesome, shouldn't it be the dependency of your package and be required from your components?

**Comment by sapegin** [comment]
Please use fenced blocks with language tags (for example ```` ```js````) to make code examples more readable.

**Comment by dbertella** [comment]
You can use an html template and include the link in the html as I was asking in another issue (#593) or as I did previously, include the whole css, I was using the scss version and include it as you are doing into the `require`. If you are doing that, and use the scss version use this variable `$fa-font-path:        "//netdna.bootstrapcdn.com/font-awesome/4.7.0/fonts" !default; // for referencing Bootstrap CDN font files directly` because it will load the fonts from the cdn and you don't have to import them

**Comment by sabhyankarxactly** [comment]
@dbertella Thanks for the pointer, I was able to use the custom template to load font-awesome icons.
@n1313 I tried loading the font-awesome CSS and font files in the stylguide.config.js require section but did not work. I do like the idea of making font-awesome a dependency of my package and load them through my components, will work on that.
