### ISSUE TITLE
Allowing "CODE" label to be changed via configuration?

### ISSUE THREAD

**Issue by aversini** [styleguidist/react-styleguidist#693]
While many places in Styleguidist are configurable, the one label that is giving trouble to our own customers is "CODE". While obvious to my teammates, it is not very clear to non-devs like Visual design or QA folks.

I've used the following configuration to reverse the uppercasing, but I was wondering if there was a way to completely change it (to something like "View code") via configuration?
Let me know, thanks!

```js
...
styles: {
  tabButton: {
    button: {
      textTransform: 'none'
    }
  }
...
```

**Comment by sapegin** [comment]
That’s a tricky question because technically it’s a plugin and it won’t be easy to make such an option. I’m fine to rename it to “View Code” by default but I feel like your question is related to general customization of this area that are discussed in #195 — if you have any ideas, feel free to comment there.

**Comment by sapegin** [comment]
We can also move `textTransform` to the theme, it will be easy to change for the whole UI.

**Comment by aversini** [comment]
Thanks @sapegin , as a first step, changing to "View Code" would help a lot. Want me to create a PR?

**Comment by sapegin** [comment]
Yep, sure!

**Comment by aversini** [comment]
Cool, here it is #697
