### ISSUE TITLE
Imported flow types support

### ISSUE THREAD

**Issue by AwK55** [styleguidist/react-styleguidist#752]
Hi. I just have a question. 
Can styleguidist add to guideline an imported flow types as it can with types that's declared in component file? If not, how it can be realized? 

thank you

**Comment by sapegin** [comment]
That’s a react-docgen limitation, there were several issues with this request I believe. But that’s not something easy to implement ;-|

**Comment by stereobooster** [comment]
This is what I see

![screen shot 2018-01-25 at 13 53 45](https://user-images.githubusercontent.com/179534/35389243-43c4e702-01d7-11e8-894f-fd6f8b947249.png)

From [react-docgen: flow-type-support](https://github.com/reactjs/react-docgen#flow-type-support). 

```js
    "func":{
      "flowType":{
        "name":"signature", // <--- pay attention
        "type":"function",  // <--- pay attention
        "raw":"(value: string) => void",
        "signature":{
          "arguments":[
            { "name":"value", "type":{ "name":"string" } }
          ],
          "return":{ "name":"void" }
        }
      },
      "required":false
    },
```

I suppose we can show`function` instead of `signature` in this situation. Can do PR for it if you agree. Maybe you will direct me where to do this in the code, but if not this is ok too.

**Comment by sapegin** [comment]
@stereobooster That's would be awesome! I have no idea what signature means ;-|

**Comment by stereobooster** [comment]
Note to myself:

https://github.com/styleguidist/react-styleguidist/blob/3df38d4e63831a725de522156d52e8e27746f0f9/src/rsg-components/Props/PropsRenderer.js#L18-L35

Stupid solution

```js
let name = type.name;
if (name === "signature" && type.type !== undefined) {
  name = type.type
}
```

instead of

```js
const { name } = type; 
```
