### ISSUE TITLE
Support ES6 exports

### ISSUE THREAD

**Issue by seivan** [styleguidist/react-styleguidist#820]
I see this issue was closed without any comments and also locked https://github.com/styleguidist/react-styleguidist/issues/633

Is there a reason only default exports are allowed and not named exports? 
We're in a position to rely on ES6 exports to allow tree shaking and would rather not use default exports.

I was wondering if there is any wiggle room here or if you stand strong on this?

**Comment by marcdavi-es** [comment]
Yeah I thought the response to #633 was close-minded. 

A lot of developers use only named exports for a bunch of reasons. `eslint-plugin-import` is in the process of adding [a rule to prohibit the use of defaults exports](https://github.com/benmosher/eslint-plugin-import/issues/889).

Without this I need to hack styleguidist to make it usable.

**Comment by seivan** [comment]
@marcdavi-es Well if you're in a hurry, you can get around it with 
```
const Button = require('./dist/Components/Button').Button;
```

But it's very error prone.

**Comment by marcdavi-es** [comment]
I had a dig around to try a more robust solution. I'm a bit puzzled by what I found.

Given this set up...

````jsx
// styleguide.config.js
module.exports = {
  components: 'path/to/component.js',
};

// path/to/component.js
import React from 'react';

export const SomeComponent = () => <div>Hello, I'm SomeComponent</div>;

// path/to/Readme.md
```js
console.log(SomeComponent);
```

````

...I see in the console `{ SomeComponent: ...,  __esModule: true}`.

That suggests that the exports of `/component.js` are exposed as `SomeComponent`. That's kind of weird because `SomeComponent` is the name of one of the named exports, not the exports as a whole.

In this case, the following 'works'...

````js
// path/to/Readme.md
```js
<SomeComponent.SomeComponent />
```
````

...which seems odd. Perhaps I'm missing something obvious here.

If a contributor is looking at this, I'm super happy to work on a potential fix. I could do with some help pointing to where the modules are expose though. So far I've had a dig around `Preview`, `evalInContext` and associated files but I haven't had any joy.

**Comment by seivan** [comment]
@marcdavi-es I just tested your idea, and as you said, it worked.

**Comment by kopax** [comment]
any update on this?

**Comment by seivan** [comment]
@kopax There's an attached PR https://github.com/styleguidist/react-styleguidist/pull/825
