### ISSUE TITLE
can't get basic styled components with @component annotation jsdoc working

### ISSUE THREAD

**Issue by longility** [styleguidist/react-styleguidist#850]
I'm not sure what I'm doing wrong. It is not picking up my component that is a styled component using annotation.

https://github.com/longility/react-styleguidist/tree/styled-component-example

```
Warning: src/components/StyledButton.js matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.

It usually happens when using third-party libraries, see possible solutions here:
https://react-styleguidist.js.org/docs/thirdparties.html
```

**Comment by sapegin** [comment]
I don't see any warnings in your example with the latest React Styleguidist.

**Comment by longility** [comment]
Thanks for responding. I decided to do the following and still got the same warning.

1. rebase to latest `master` on react-styleguidist.
2. `git clean -xdf`
3. `cd examples/cra/`
4. `npm install`
5. `npm run styleguide`

Besides making sure I have a clean environment and latest react-styleguidist, did you do anything different? Maybe you can guide me on debugging. I'm not sure where to go from here.

**Comment by sapegin** [comment]
This is not the latest version:

https://github.com/styleguidist/react-styleguidist/blob/a086302bbef484144f6dbfe4ff43e143b68aff47/examples/cra/package.json#L20

**Comment by longility** [comment]
Thank you for your help! I didn't think about upgrading rsg npm package in the example. I'm now able to get it working.

**Comment by glensomerville** [comment]
I'm running into this same issue with Styled Components and TypeScript. Any suggestions on what might be going wrong here?

Error:
`Warning: src/components/Buttons/MediumButton/MediumButton.tsx matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.`

https://github.com/glensomerville/react-styled-components-styleguide-ts

**Comment by glensomerville** [comment]
Yes, the example repo can be found here: https://github.com/glensomerville/react-styled-components-styleguide-ts

Thanks for looking into this.

**Comment by glensomerville** [comment]
Oh, and by the way, if I change a direct styled-component export to a SFC, then it is picked up correctly.

e.g. instead of exporting a styled element directly, as in https://github.com/glensomerville/react-styled-components-styleguide-ts/blob/master/src/components/Buttons/MediumButton/MediumButton.tsx, it will work if I change it to:

`
import * as React from 'react';
import { styled } from 'themes';

const StyledMediumButton = styled.button`
  width: 320px;
  height: 40px;
  border-radius: 4px;
  border: solid 1px ${props => props.theme.colors.powderBlue};
  text-align: center;
  font-family: ${props => props.theme.fonts.primary};
  font-size: 13px;
  font-weight: 900;
  color: ${props => props.theme.colors.darkishBlue};
  text-transform: uppercase;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: ${props => props.theme.colors.whiteTwo};
  &:hover {
    color: ${props => props.theme.colors.cerulean};
    border-color: ${props => props.theme.colors.cerulean};
  }
`;

const MediumButton: React.SFC<{}> = ({ children }) => {
  return (
    <StyledMediumButton>
      {children}
    </StyledMediumButton>
  );
};

export default MediumButton;
`

**Comment by kellyisworking** [comment]
Hi @glensomerville were you able to find a fix? *I think* I'm having the same issue.
