### ISSUE TITLE
withTheme() higher order component of styled-component isn't working with react-styleguidist

### ISSUE THREAD

**Issue by pnepe6** [styleguidist/react-styleguidist#867]
withTheme() higher order component of styled-component isn't working. Is something possible to fix this ?

You can take a look at [this example](https://paste.gnome.org/p7hqkzht0)

Thanks in advance, react-styleguidist is awesome.

**Comment by kopax** [comment]
You are using `/** @component */` on a non styled components.
If you are having a styled components in between, just use `withTheme` HoC before styled otherwise you are wrapping your component one last time with the default exports and **static** `defaultProps` and `propTypes` won't be present.

Otherwise, you can also do : 

```jsx
const Hoc = withTheme(Alert)
Hoc.propTypes = propTypes;
Hoc.defaultProps = defaultProps;
export default HoC;
```

**Comment by pnepe6** [comment]
Solution 2 works, thank you so much.
